version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumen_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: ["sh", "-c", "composer install --no-dev --optimize-autoloader && php -S 0.0.0.0:8000 -t public"]
    environment:
      - OPENSEARCH_HOST=http://opensearch:9200
    depends_on:
      - opensearch
    networks:
      - app_network

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch
    restart: always
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true  # Disable security for development
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin  # Set admin password
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9600:9600"  # Internal monitoring
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - app_network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: opensearch-dashboards
    restart: always
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true  # Disable security for dashboards
    depends_on:
      - opensearch
    networks:
      - app_network

volumes:
  opensearch_data:

networks:
  app_network:
    driver: bridge
